//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BagsStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string DropOff { get; set; }
        public string PickUp { get; set; }
        public string Bags { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Location { get; set; }
        public string StoreName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Price { get; set; }
        public string PaymentMethod { get; set; }
        public string Street { get; set; }
        public string WHours { get; set; }
        public string MapPicture { get; set; }
        public string Link { get; set; }
        public string EmailConf { get; set; }
        public string Additional { get; set; }
    }
}
