//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BagsStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Street { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Type { get; set; }
        public string WorkingHours { get; set; }
        public string Price { get; set; }
        public string Picture { get; set; }
        public Nullable<bool> Partner { get; set; }
        public Nullable<int> Location { get; set; }
        public string Email { get; set; }
        public string MapPicture { get; set; }
        public string Link { get; set; }
        public string RealName { get; set; }
        public string HourFrom { get; set; }
        public string HourTo { get; set; }
        public string Services { get; set; }
        public string DayOff { get; set; }
        public string Additional { get; set; }
        public string PictureMobile { get; set; }
    }
}
